theme: jekyll-theme-hacker
title: Welcome to McKenzie Steenson's homepage!
description: It's the start of something new!

![Image of husky puppy]
(https://i.ebayimg.com/00/s/NzUzWDEwMjQ=/z/bCwAAOSwTM5YtzZy/%24_86.JPG)
